import { StyleSheet } from "react-native";
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      height: hp('100%'), // 70% of height device screen
      width: wp('100%')   // 80% of width device screen
    },
    box: {
      // backgroundColor: "#127885",
      flex: 0.6,
      width: wp('100%'),
      alignItems: "center",
      justifyContent: "center",
      borderRadius:10,
    },
    box2: {
      flex: 2,
      width: wp('90%'),
      borderRadius:20,
      backgroundColor: "white",
      alignItems: "center",
      justifyContent: 'flex-start',
    },
    box3: {
      flex: 1,
      width: wp('100%'),
      // backgroundColor: "white",
      alignItems: "center",
    },
    boxButton: {
      flex: 1,
      width: wp('100%'),
      height:"100%",
      backgroundColor: "transparent",
      alignItems: "center",
    },
    boxflat: {
      flex: 2,
      width: wp('100%'),
      backgroundColor: "white",
      alignItems: "center",
      justifyContent: "center",
    },
    boxCam: {
      flex: 2,
      width: wp('90%'),
      backgroundColor: "white",
      alignItems: "center",
      marginBottom:wp(40),
      marginTop:hp(5),
      justifyContent: "center",
      height:hp(1),
      borderRadius:50,
    },
    fab: { 
      position: 'absolute', 
      width: wp('45%'),
      height: hp(7), 
      alignItems: 'center', 
      justifyContent: 'center',  
      bottom: hp(1), 
      backgroundColor: '#03A9F4', 
      borderRadius: 30, 
      }, 
    fabIcon: { 
      fontSize: hp(3), 
      color: 'white' 
    },
    // messageContainer: {
    //     zIndex: 1,
    //     position: 'absolute',
    //     top:0,
    //     right: 0,
    //     left: 0,
    //     height: 80,
        // alignItems: 'center',
    // },
    // bubble: {
    //     paddingHorizontal: 20,
    //     paddingVertical: 10,
    //     borderRadius: 20,
    //     backgroundColor: 'red',
    // },
    // text: {
    //     color: 'white',
    // },
  })
  const components = StyleSheet.create({
    item: {
      justifyContent:'center',
      paddingLeft:10,
      marginVertical: 8,
      marginHorizontal: 16,
      backgroundColor:'#5bb',
      borderRadius:25,
      borderWidth:2,
      borderColor:'#d4e1ea',
      height: hp('12%'),
      width: wp('65%'),
    },
    item2: {
      marginTop:hp(2),
      justifyContent:'space-around',
      alignItems:'center',
      marginVertical: 8,
      position:"absolute",
      backgroundColor:'#18A1B2',
      borderRadius:50,
      borderWidth:2,
      borderColor:'#d4e1ea',
      height: hp('9%'),
      width: wp(20),
    },
    title: {
      fontSize: hp('4%'),
    },
    buttonPrimary: {
      width: wp('52%'),
      height: hp(7),
      // backgroundColor:'#127885',
      elevation:8,
      paddingTop: hp('0.75%'),
      borderRadius:20, 
      // borderWidth:0,
      paddingVertical: hp('0.5%'), 
      paddingHorizontal: wp('0.5%'),
      marginTop:hp(3),
    },
    buttonAdd: {
      width: '30%',
      height: '50%',
      fontSize:15,
      backgroundColor:'#127885',
      elevation:8,
      borderRadius:10, 
      paddingVertical:10, 
      paddingHorizontal:12,
    },
    buttonDanger: {
      width: '30%',
      backgroundColor:'#8ee5f0',
      height: '20%',
      elevation:8,
      borderRadius:10, 
      paddingVertical:10, 
      paddingHorizontal:12,
    },
    buttonText:{
      fontSize: hp('3%'),
      color: '#fff',
      fontWeight: "bold",
      alignSelf:'center',
      padding:hp('0.75'),
    },
    input: {
      width: wp('80%'),
      height: hp('7%'),
      backgroundColor: "#d9e8ef",
      marginTop:hp(4),
      padding: 8,
      borderRadius: 14,
      fontSize: hp(2.5),
      fontWeight: "500",
      color:"#1ca5c5"
    },
    scan: {
      fontSize: 18,
      fontWeight: "bold",
      height: 50,
      borderRadius:20,
    },
  })
export { styles, components }
  